'use client';
import ThemeToggle from './theme-toggle';
import { useState, useEffect, useRef } from 'react';
import { ArrowUpRight, ArrowDown, Download, MapPin, Layers, Database, Braces, Cloud, ArrowRight, Mail, Check, Copy, Menu, X, Terminal, GraduationCap } from 'lucide-react';
const projects = [
 {name:'Mojoenet CRM',category:'Business systems',type:'ISP OPERATIONS PLATFORM',year:'2026 — Present',description:'Bringing customers, billing, and service operations together.',detail:'Led development of a Laravel 12 and Livewire ISP CRM covering customers, leads, invoicing, payments, SMS, support tickets, and service operations. Modernized legacy workflows with migrations, queues, bulk processing, and automation.',tags:['Laravel 12','Livewire','MySQL'],art:'crm'},
 {name:'Myanmar Teacher Platform',category:'Web platforms',type:'LEARNING MANAGEMENT SYSTEM',year:'2023 — 2025',description:'A stronger foundation for learning at scale.',detail:'Built and scaled a Laravel and Vue.js learning platform. Led the migration of 1M+ assets and approximately 800GB from AWS to Azure with near-zero downtime, and improved production reliability.',tags:['Laravel','Vue.js','Azure'],art:'learn'},
 {name:'BaganPay',category:'Payments',type:'PAYMENT INTEGRATION',year:'2020 — 2022',description:'Reliable payment flows. Every transaction accounted for.',detail:'Built a secure Laravel and MySQL payment platform with payment gateway integrations and real-time transaction tracking.',tags:['Laravel','MySQL','Payment APIs'],art:'pay'},
 {name:'Lemonaide DMS',category:'Business systems',type:'AUTOMOTIVE DATA PLATFORM',year:'2022 — 2023',description:'Turning complex vehicle data into useful workflows.',detail:'Developed a Laravel and Vue.js data management platform for used cars, with GraphQL APIs and optimized data processing workflows.',tags:['Laravel','Vue.js','GraphQL'],art:'data'},
 {name:'School Management System',category:'Business systems',type:'FREELANCE · SCHOOL OPERATIONS',year:'2025 — Present',description:'Connected school operations, from classrooms to payments.',detail:'Built APIs for mobile apps, automated invoicing, SMS alerts, and secure MMQR payment integration to streamline school operations.',tags:['REST APIs','MMQR','SMS'],art:'school'},
 {name:'Smile Shop',category:'Payments',type:'FREELANCE · E-COMMERCE',year:'2024 — 2025',description:'The backend behind a seamless shopping experience.',detail:'Designed and developed the CMS and APIs for an e-commerce platform, including integration with secure payment systems.',tags:['CMS','REST APIs','Payments'],art:'shop'},
 {name:'Shwe Nar Sin',category:'Web platforms',type:'AUDIOBOOK PLATFORM',year:'2018 — 2022',description:'A reliable home for stories worth listening to.',detail:'Developed a Laravel and MySQL audio platform with subscription features, caching, and content management tools.',tags:['Laravel','MySQL','Caching'],art:'audio'},
 {name:'WunZinn To Home',category:'Web platforms',type:'ONLINE BOOKSTORE',year:'2019 — 2022',description:'Connecting readers with their next favorite book.',detail:'Built Laravel and MySQL backend systems with SMS integration, reporting tools, and CMS features for an online bookstore.',tags:['Laravel','MySQL','SMS'],art:'books'},
];
const jobs = [
 ['Jan 2026 — Present','Full-Stack Developer','Brndwrx','Bangkok, Thailand','Leading an ISP operations portal and modernizing legacy systems with automated data sync, queues, bulk SMS, and invoice processing.'],
 ['Dec 2023 — Dec 2025','Senior Backend Engineer','Impulseinternational','Yangon, Myanmar','Led backend development and a large-scale AWS-to-Azure migration. Designed cloud infrastructure and resolved critical production stability issues.'],
 ['Sep 2022 — Aug 2023','Full Stack Developer','WSmart (Lemonaide)','Bangkok, Thailand','Built Laravel and Vue.js platforms, translating business requirements into responsive, tailored web applications.'],
 ['Jan 2018 — Aug 2022','Backend Developer','Bagan Innovation Technology','Yangon, Myanmar','Developed production APIs and systems for high-volume content, reporting, and transactions, with a focus on reliability and data integrity.'],
];
function ProjectArt({kind}:{kind:string}) { return <div className={`project-art ${kind}`} aria-hidden="true">{kind==='crm'?<div className="mini-window"><div className="mini-sidebar"><b>m.</b><i/><i/><i/><i/></div><div className="mini-content"><div className="mini-top">Workspace overview <span>•••</span></div><div className="mini-stats"><div>Customers<strong>Connected</strong><small>All in one place</small></div><div>Operations<strong>In sync</strong><small>Built for clarity</small></div></div><div className="mini-chart">{[35,52,43,69,58,82,71,95,86,110,102,125].map((h,i)=><i key={i} style={{height:h/1.8}}/>)}</div></div></div>:kind==='learn'?<div className="learning-visual"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><div className="learning-icon"><GraduationCap size={42} strokeWidth={1.3}/></div><span className="floating-label label-one"><Cloud size={14}/> Built to scale</span><span className="floating-label label-two"><Layers size={14}/> Connected learning</span></div>:kind==='pay'?<div className="payment-visual"><div className="bank-card"><span>BaganPay <Layers size={19}/></span><div className="chip"/><strong>•••• &nbsp; •••• &nbsp; •••• &nbsp; 2020</strong><small>SECURE BY DESIGN</small></div><div className="payment-badge"><span><Check size={15}/></span> Payment processed</div></div>:<div className="generic-visual"><Database size={42} strokeWidth={1}/><div>{kind==='data'?'Data, organized.':kind==='school'?'Operations, connected.':kind==='shop'?'Commerce, connected.':kind==='audio'?'Stories, streaming.':'Books, delivered.'}</div><span>API → APPLICATION → EXPERIENCE</span></div>}</div> }
export default function Home(){const [filter,setFilter]=useState('All projects');const [selected,setSelected]=useState<number|null>(null);const [copied,setCopied]=useState(false);const [menu,setMenu]=useState(false);const [expanded,setExpanded]=useState(false);const dialogRef=useRef<HTMLDialogElement>(null);useEffect(()=>{if(selected!==null){dialogRef.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};}},[selected]);const filtered=projects.filter(p=>filter==='All projects'||p.category===filter);const visible=expanded?filtered:filtered.slice(0,3);async function copy(){try{await navigator.clipboard.writeText('kaungmyatsan154996@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{window.location.href='mailto:kaungmyatsan154996@gmail.com';}}
return <><a className="skip-link" href="#main">Skip to content</a><header><a href="#" className="logo" aria-label="Kaung Myat San home">k<span>ms</span><i>.</i></a><div className="header-actions"><nav className={menu?'open':''} aria-label="Main navigation">{['Work','Experience','About'].map(s=><a key={s} href={`#${s.toLowerCase()}`} onClick={()=>setMenu(false)}>{s}</a>)}<a className="nav-contact" href="#contact" onClick={()=>setMenu(false)}>Let’s talk <ArrowUpRight size={15}/></a></nav><ThemeToggle/><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
<main id="main"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> BACKEND & FULL-STACK ENGINEER</div><h1>Engineering<br/>what’s <span>next.</span></h1><p className="intro">Hi, I’m <strong>Kaung Myat San.</strong> I build the reliable systems<br className="desktop-break"/> behind thoughtful digital experiences.</p><p className="hero-description">7+ years turning complex business challenges into scalable<br className="desktop-break"/> platforms — from the first API to production and beyond.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowUpRight size={17}/></a><a className="resume-link" href="/Kaung_Myat_San.pdf" download>Download résumé <Download size={15}/></a></div><div className="location"><MapPin size={14}/> Bangkok, Thailand <span/> Building with purpose, across borders.</div></div></section>
<div className="stack-ribbon"><span>MY CORE STACK</span><strong>Laravel</strong><i>✳</i><strong>PHP</strong><i>✳</i><strong>Vue.js</strong><i>✳</i><strong>MySQL</strong><i>✳</i><strong>AWS / Azure</strong></div><div className="proof-strip"><div><strong>7+</strong><span>Years of experience</span></div><div><strong>1M+</strong><span>Assets migrated</span></div><div><strong>~800<span>GB</span></strong><span>Moved to the cloud</span></div><div className="proof-note"><span className="small-cross">✳</span><p>Built for performance.<br/>Made to last.</p></div></div>
<section className="work section" id="work"><div className="section-heading"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Selected work<span className="heading-period">.</span></h2></div><p>A selection of platforms I’ve helped<br/>build, scale, and keep running.</p></div><div className="filters" aria-label="Filter projects">{['All projects','Business systems','Web platforms','Payments'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>{setFilter(f);setExpanded(false);}} aria-pressed={filter===f}>{f}{f==='All projects'&&<span>08</span>}</button>)}</div><div className="project-grid">{visible.map(p=><button className={`project-card ${p.art==='crm'?'featured-project':''}`} key={p.name} onClick={()=>setSelected(projects.indexOf(p))}><ProjectArt kind={p.art}/><div className="project-body"><div className="project-type">{p.type}<ArrowUpRight size={17}/></div><div className="project-year">{p.year}</div><h3>{p.name}</h3><p>{p.description}</p>{p.art==='crm'&&<p className="featured-description">An end-to-end operations platform connecting customer management, billing, support, and automated workflows.</p>}<div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-read">Explore project <ArrowUpRight size={15}/></div></div></button>)}</div>{filtered.length>3&&<button className="more-projects" onClick={()=>setExpanded(!expanded)}>{expanded?'Show less':'View all projects'} <ArrowDown size={15} style={{transform:expanded?'rotate(180deg)':undefined}}/></button>}</section>
<section className="experience section" id="experience"><div className="section-heading"><div><div className="eyebrow">02 / THE JOURNEY</div><h2>Experience that <span>adds up.</span></h2></div><a className="text-link" href="/Kaung_Myat_San.pdf" download>Full résumé <ArrowUpRight size={16}/></a></div><div className="timeline">{jobs.map((j,i)=><article className="job" key={j[2]}><div className="job-date"><span className={i===0?'timeline-dot current':'timeline-dot'}/>{j[0]}{i===0&&<span className="current-label">CURRENT</span>}</div><div><h3>{j[1]}</h3><div className="company">{j[2]} <span>· {j[3]}</span></div><p>{j[4]}</p></div></article>)}</div></section>
<section className="about section" id="about"><div className="about-copy"><div className="eyebrow">03 / A LITTLE ABOUT ME</div><h2>Behind the code,<br/><span>a systems thinker.</span></h2><p>I’m a backend and full-stack engineer based in Bangkok. I enjoy making complicated things work simply — whether that’s a payment flow, a cloud migration, or the everyday operations of a business.</p><p>My work centers on reliability, performance, and maintainability. I take ownership from architecture through deployment, building systems that teams can trust and continue to grow.</p><div className="education"><GraduationCap size={24}/><div><strong>Bachelor of Computer Science</strong><span>Computer University, Pyay · 2012 — 2017</span></div></div></div><div className="toolkit"><div className="toolkit-title"><Terminal size={17}/> MY EVERYDAY TOOLKIT</div>{[[Braces,'Backend & APIs','Laravel · PHP · REST APIs · GraphQL'],[Layers,'Frontend','Vue.js · Livewire'],[Database,'Data & infrastructure','MySQL · AWS · Azure · Queues'],[Cloud,'Integrations','Payment gateways · MMQR · SMS']].map(([Icon,title,desc])=>{const I=Icon as typeof Braces;return <div className="tool-row" key={String(title)}><span><I size={20}/></span><div><h3>{String(title)}</h3><p>{String(desc)}</p></div></div>})}</div></section>
<section className="contact" id="contact"><div><div className="eyebrow"><span className="status-dot"/> LET’S BUILD SOMETHING THAT MATTERS</div><h2>Have a challenge in mind?<br/><span>Let’s figure it out.</span></h2><p>From a new idea to a system that needs a stronger foundation.</p></div><div className="contact-actions"><a className="button primary" href="mailto:kaungmyatsan154996@gmail.com">Start a conversation <ArrowUpRight size={17}/></a><button className="copy-email" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}<span aria-live="polite">{copied?'Email copied!':'Copy email address'}</span></button></div></section></main><footer><a href="#" className="logo">k<span>ms</span><i>.</i></a><p>© {new Date().getFullYear()} Kaung Myat San</p><span>Thoughtfully built. Always improving.</span><a href="mailto:kaungmyatsan154996@gmail.com" aria-label="Email Kaung"><Mail size={18}/></a></footer>
{selected!==null&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><dialog ref={dialogRef} className="project-dialog" aria-labelledby="dialog-title" onCancel={()=>setSelected(null)} onClick={e=>e.stopPropagation()}><button className="close-dialog" onClick={()=>setSelected(null)} aria-label="Close project details" autoFocus><X size={20}/></button><ProjectArt kind={projects[selected].art}/><div className="dialog-content"><div className="eyebrow">{projects[selected].type}</div><h2 id="dialog-title">{projects[selected].name}</h2><span className="dialog-year">{projects[selected].year}</span><p>{projects[selected].detail}</p><div className="tags">{projects[selected].tags.map(t=><span key={t}>{t}</span>)}</div></div></dialog></div>}</>}
